4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

In [17]:
#1. Initialize an empty array with size 2X2.

import numpy as np

empty_array = np.empty((2,2))
print(empty_array)

[[6.95334570e-310 8.29683145e-312]
 [8.29683145e-312 8.29683145e-312]]


In [4]:
#Initialize an all one array with size 4X2.

import numpy as np

ones_array = np.ones((4,2))
print(ones_array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
#3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

import numpy as np

# Define the shape, type, and fill value
shape = (6, 6)  
dtype = np.int32  
fill_value = 6  

# Create the array
filled_array = np.full(shape, fill_value, dtype=dtype)
print(filled_array)

[[6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]
 [6 6 6 6 6 6]]


In [12]:
#4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros_like}

import numpy as np

a = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

zeros_array = np.zeros_like(a)
print(zeros_array)

[[0 0 0 0]
 [0 0 0 0]]


In [13]:
#5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

import numpy as np

a = np.array([[1, 2, 3, 4], [4, 5, 6, 7]])

ones_array = np.ones_like(a)
print(ones_array)

[[1 1 1 1]
 [1 1 1 1]]


In [16]:
#6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

import numpy as np

new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print(numpy_array)

[1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing: 

In [18]:
#1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

import numpy as np

array_range = np.arange(10, 50)
print(array_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [19]:
#2. Create a 3X3 matrix with values ranging from 0 to 8.{Hint:look for np.reshape()}

import numpy as np

matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [20]:
#3. Create a 3X3 identity matrix.{Hint:np.eye()}

import numpy as np

identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [21]:
#4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}

import numpy as np

# Create a random array of size 30
random_array = np.random.random(30)

# Calculate the mean
mean_value = random_array.mean()
print(mean_value)

0.5234185845081214


In [22]:
#5. Create a 10X10 array with random values and find the minimum and maximum values.

import numpy as np

# Create a 10x10 array with random values
random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.007267554154343547
Maximum value: 0.9899299240324703


In [23]:
#6. Create a zero array of size 10 and replace 5th element with 1.

import numpy as np

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element with 1
zero_array[4] = 1

print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [26]:
#7. Reverse an array arr = [1,2,0,0,4,0].

import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]  
print(reversed_arr)

[0 4 0 0 2 1]


In [32]:
#8. Create a 2d array with 1 on border and 0 inside.

import numpy as np

# Define the size of the array
rows = 3 # Number of rows
cols = 3  # Number of columns

# Create an array with all ones
array_2d = np.ones((rows, cols), dtype=int)  

# Set the inner elements to 0
array_2d[1:rows-1, 1:cols-1] = 0  

print(array_2d)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


In [36]:
#9. Create a 8X8 matrix and fill it with a checkerboard pattern.

import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

In [1]:
#1. Add the two array.

import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Addition
addition_result = x + y 
print(addition_result)

[[ 6  8]
 [10 13]]


In [2]:
#2. Subtract the two array.
# Subtraction
subtraction_result = x - y  
print(subtraction_result)

[[-4 -4]
 [-4 -3]]


In [3]:
#3. Multiply the array with any integers of your choice.
# Multiplication with an integer
integer_multiplier = 3  # Choose any integer
multiplication_result = x * integer_multiplier  
print(multiplication_result)

[[ 3  6]
 [ 9 15]]


In [4]:
#4. Find the square of each element of the array.
# Square of each element
square_result = x**2  
print(square_result)

[[ 1  4]
 [ 9 25]]


In [5]:
#5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
v = np.array([9, 10])
w = np.array([11, 12])

# Dot product between v and w
dot_product_vw = np.dot(v, w)  
print(dot_product_vw)

# Dot product between x and v
dot_product_xv = np.dot(x, v)  
print(dot_product_xv)

# Dot product between x and y
dot_product_xy = np.dot(x, y)  
print(dot_product_xy)

219
[29 77]
[[19 22]
 [50 58]]


In [6]:
#6. Concatenate x(and)y along row and Concatenate v(and)w along column.{Hint:try np.concatenate() or np.vstack() functions.
# Concatenate x and y along row
row_concatenation = np.concatenate((x, y), axis=0)  
print(row_concatenation)

# Concatenate v and w along column
column_concatenation = np.vstack((v, w))  
print(column_concatenation)

[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
#7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
# Attempt to concatenate x and v
# concatenation_result = np.concatenate((x, v), axis=0)  # This will raise an error

For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:

In [7]:
#1. Prove A.A^−1 = I.
import numpy as np

A = np.array([[3, 4], [7, 8]])
A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

# Check if result is approximately equal to identity matrix
identity_matrix = np.eye(2)
print(np.allclose(result, identity_matrix))

True


In [12]:
#2. Prove AB ̸= BA.
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

# Check if AB is not equal to BA
print(np.array_equal(AB, BA))  # This should print False

print("AB:")
print(AB)
print("BA:")
print(BA)

False
AB:
[[23 13]
 [51 29]]
BA:
[[36 44]
 [13 16]]


In [13]:
#3. Prove (AB)^T = B^TA^T


AB_T = np.transpose(AB)

B_T = np.transpose(B)
A_T = np.transpose(A)
B_TA_T = np.dot(B_T, A_T)

# Check if (AB)^T is equal to B^T A^T
print(np.array_equal(AB_T, B_TA_T))  # This should print True

print("(AB)^T:")
print(AB_T)
print("B^T A^T:")
print(B_TA_T)

True
(AB)^T:
[[23 51]
 [13 29]]
B^T A^T:
[[23 51]
 [13 29]]


Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [14]:
import numpy as np

# Define matrices A and B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Display the result
print("Solution:")
print(X)

Solution:
[ 2.  1. -2.]


Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [15]:
import numpy as np

# Define matrices A and B
A = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
B = np.array([-1, -3, 9])

# Calculate the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X
X = np.dot(A_inv, B)

# Display the result
print("Solution (x, y, z):")
print(X)

Solution (x, y, z):
[ 2.  1. -2.]
